name: Test Manual Versioning

env:
  CI: true
  GITHUB_BUILD_NUMBER: ${{ github.run_number }}
  GITHUB_BUILD_ID: ${{ github.run_id }}
  GITHUB_TOKEN: ${{ secrets.AHMAD_GITHUB_TOKEN }}


on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:
  release:
    name: Push Event
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git user
        run: |
          git config --global user.email "ahmed.elkhateeb@ww.com"
          git config --global user.name "Ahmad Elkhateeb"
      - name: Check branch name and extract version
        run: |
          echo Checking name of Branch ${GITHUB_REF##*/}
          branch_name=${GITHUB_REF##*/}
          pattern="^release-v\.[0-9]+\.[0-9]+\.[0-9]+$"

          if [[ $branch_name =~ $pattern ]]; then
            version=${branch_name#release-v.}
            echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
          else
            echo "Branch name doesn't match the desired pattern!"
            exit 1
          fi
      - name: Run Release It
        run: |
          if [[ -z "${RELEASE_VERSION}" ]]; then
            echo "Release version not found. Exiting."
            exit 1
          fi
          echo Pushing on Branch ${GITHUB_REF##*/}
          npm ci
          npm run release-ci

  deploy-main:
    name: Deploy To Main
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && !github.event.release.prerelease
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo Running Release on Branch ${GITHUB_REF##*/}
