name: Test Manual Versioning

env:
  CI: true
  GITHUB_BUILD_NUMBER: ${{ github.run_number }}
  GITHUB_BUILD_ID: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:
  release:
    name: Push Event
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo Pushing on Branch ${GITHUB_REF##*/}
  deploy-main:
    name: Deploy To Main
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && !github.event.release.prerelease
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo Running Release on Branch ${GITHUB_REF##*/}
